  
name: Context_TEST

on: push

jobs:
  TEST-001:
    runs-on: ubuntu-latest
    steps:     
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: "context"
        env:
          COMMIT_ID: ${{ github.sha }}
        run: echo "Commit id => $COMMIT_ID"
        


      - name: ls -la
        run: ls -la
