  
name: Context_TEST

on: push

jobs:
  TEST-001:
    runs-on: self-hosted
    steps:     
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: "context"
        env:
          COMMIT_ID: ${{ github.sha }}
        run: echo "Commit id => $COMMIT_ID"
      
      - name: ls -la
        run: ls -la
        
      - name: github.sha
        run: echo "${{ github.sha }}"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
        
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build
