  
name: Context_TEST

on: push

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: "context"
        env:
          COMMIT_ID: ${{ github.sha }}
        run: echo "Commit id => $COMMIT_ID"
